### ISSUE TITLE
Can't install from requirements file via chef / bash script - but I can manually

### ISSUE THREAD

**Issue by cnk** [Brobin/django-seed#10]
When I try to install django-seed by running `pip install -r requirements.txt` I get the following stack trace complaining about django-seed's setup.py not being able to import django. As you can see from the earlier output of the command, Django 1.8 is installed in the VE before django-seed is requested so I am not sure why the import fails. 

       ---- Begin output of "bash"  "/tmp/chef-script20150528-12312-12cu373" ----
       STDOUT: Collecting Django>=1.8 (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 1))
         Using cached Django-1.8.2-py2.py3-none-any.whl
       Collecting psycopg2 (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 2))
         Using cached psycopg2-2.6.tar.gz
       Collecting django-suit (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 3))
         Using cached django-suit-0.2.13.tar.gz
       Collecting django-suit-ckeditor (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 4))
         Using cached django-suit-ckeditor-0.0.2.tar.gz
       Collecting gunicorn (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 5))
         Using cached gunicorn-19.3.0-py2.py3-none-any.whl
       Collecting pytz (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 6))
         Using cached pytz-2015.4-py2.py3-none-any.whl
       Collecting django-seed (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 7))
         Using cached django-seed-0.1.2.tar.gz
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):
             File "<string>", line 20, in <module>
             File "/tmp/pip-build-56d4f_m7/django-seed/setup.py", line 6, in <module>
        version=__import__('django_seed').__version__,
             File "/tmp/pip-build-56d4f_m7/django-seed/django_seed/__init__.py", line 2, in <module>
        from django.conf import settings
           ImportError: No module named 'django'
           
           ----------------------------------------
       STDERR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-56d4f_m7/django-seed
       ---- End output of "bash"  "/tmp/chef-script20150528-12312-12cu373" ----
       Ran "bash"  "/tmp/chef-script20150528-12312-12cu373" returned 1
       [2015-05-28T18:17:35+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully \
(exit code 1)

Logging into the same server, removing and recreating the ve, then installing from a pip command works fine: 

(ve)$ pip install -r current/requirements.Linux.txt
pip install -r current/requirements.Linux.txt
Collecting Django>=1.8 (from -r current/requirements.Linux.txt (line 1))
  Downloading Django-1.8.2-py2.py3-none-any.whl (6.2MB)
    100% |████████████████████████████████| 6.2MB 126kB/s
^[[?25hCollecting psycopg2 (from -r current/requirements.Linux.txt (line 2))
  Downloading psycopg2-2.6.tar.gz (367kB)
    100% |████████████████████████████████| 368kB 1.7MB/s
^[[?25hCollecting django-suit (from -r current/requirements.Linux.txt (line 3))
  Downloading django-suit-0.2.13.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 494kB/s
^[[?25hCollecting django-suit-ckeditor (from -r current/requirements.Linux.txt (line 4))
  Downloading django-suit-ckeditor-0.0.2.tar.gz (686kB)
    100% |████████████████████████████████| 688kB 1.1MB/s
^[[?25hCollecting gunicorn (from -r current/requirements.Linux.txt (line 5))
  Downloading gunicorn-19.3.0-py2.py3-none-any.whl (110kB)
    100% |████████████████████████████████| 110kB 4.6MB/s
^[[?25hCollecting pytz (from -r current/requirements.Linux.txt (line 6))
  Downloading pytz-2015.4-py2.py3-none-any.whl (475kB)
    100% |████████████████████████████████| 475kB 1.5MB/s
^[[?25hCollecting django-seed (from -r current/requirements.Linux.txt (line 7))
Collecting fake-factory>=0.5.0 (from django-seed->-r current/requirements.Linux.txt (line 7))
Building wheels for collected packages: psycopg2, django-suit, django-suit-ckeditor
  Running setup.py bdist_wheel for psycopg2
  Stored in directory: /home/gunicorn/.cache/pip/wheels/ab/0c/9d/317c0ed55c67242a8f2de674f843a608eda4b8a45c73ff01a9
  Running setup.py bdist_wheel for django-suit
  Stored in directory: /home/gunicorn/.cache/pip/wheels/cc/b6/75/9f5a95b7dc77583e563bfaccd73d07c1b9a8826bc0ca102667
  Running setup.py bdist_wheel for django-suit-ckeditor
  Stored in directory: /home/gunicorn/.cache/pip/wheels/28/46/2d/d952b70457a04354e8759073422f362a37e2c8117c62e1c45b
Successfully built psycopg2 django-suit django-suit-ckeditor
Installing collected packages: Django, psycopg2, django-suit, django-suit-ckeditor, gunicorn, pytz, fake-factory, djang\
o-seed
Successfully installed Django-1.8.2 django-seed-0.1.2 django-suit-0.2.13 django-suit-ckeditor-0.0.2 fake-factory-0.5.1 \
gunicorn-19.3.0 psycopg2-2.6 pytz-2015.4

**Comment by cnk** [comment]
For anyone with a similar issue, I have no idea why I was having trouble with pip, django-seed, and a bash script run from chef. But using the python_pip recipe from the python cookbook worked fine: 

python_pip "#{project_root}/current/requirements.Linux.txt" do
        user node['dev-django-skeleton']['user']
        group node['dev-django-skeleton']['group']
        virtualenv "#{project_root}/ve"
        options "-r"
        only_if { File.exist?("#{project_root}/current/requirements.Linux.txt") }
end

**Comment by cnk** [comment]
I take it back, a clean install still fails - even with the python_pip stanza above. Same error as before about not being able to import django.config 

```
         * python_pip[/srv/ads/django/mk_web_core/current/requirements.Linux.txt] action install
           
           ================================================================================
           Error executing action `install` on resource 'python_pip[/srv/ads/django/mk_web_core/current/requirements.Linux.txt]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /srv/ads/django/mk_web_core/ve/bin/pip install -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt ----
           STDOUT: Collecting Django>=1.8 (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 1))
             Downloading Django-1.8.2-py2.py3-none-any.whl (6.2MB)
           Collecting psycopg2 (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 2))
             Downloading psycopg2-2.6.tar.gz (367kB)
           Collecting django-suit (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 3))
             Downloading django-suit-0.2.13.tar.gz (1.4MB)
           Collecting django-suit-ckeditor (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 4))
             Downloading django-suit-ckeditor-0.0.2.tar.gz (686kB)
           Collecting gunicorn (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 5))
             Downloading gunicorn-19.3.0-py2.py3-none-any.whl (110kB)
           Collecting pytz (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 6))
             Downloading pytz-2015.4-py2.py3-none-any.whl (475kB)
           Collecting django-seed (from -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt (line 7))
             Downloading django-seed-0.1.2.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-hg1ava96/django-seed/setup.py", line 6, in <module>
            version=__import__('django_seed').__version__,
          File "/tmp/pip-build-hg1ava96/django-seed/django_seed/__init__.py", line 2, in <module>
            from django.conf import settings
       
        
        ----------------------------------------
           STDERR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hg1ava96/django-seed
           ---- End output of /srv/ads/django/mk_web_core/ve/bin/pip install -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt ----
           Ran /srv/ads/django/mk_web_core/ve/bin/pip install -r /srv/ads/django/mk_web_core/current/requirements.Linux.txt returned 1

```

**Comment by Brobin** [comment]
I think the suspect line is this (in `setup.py`):

```python
version=__import__('django_seed').__version__,
```

When it goes to import the version it runs the imports in the `__init__.py` file. I think it fails because it is building everything in tmp directories and perhaps django technically doesn't exist in the environment yet. I'm not exactly sure about the internals of pip, but this is my best guess.

I won't have time to look into this for a while, but if you figure anything else out, please let me know.
