### ISSUE TITLE
When can the latest version (0.3.0) be installed through pip?

### ISSUE THREAD

**Issue by JunHyunJunHyun** [Brobin/django-seed#104]
When can the latest version (0.3.0) be installed through pip? The 0.2.2 version is still being installed.

I want to automate arrayfield, but it is impossible.

**models.py**
```
rules = ArrayField(models.TextField(), blank=False, size=6, null=True)
```

**seed.py**
```
def handle(self, *args, **options):
        total = options.get("total")
        seeder = Seed.seeder()
        seeder.add_entity(
            model~,
            total,
            {
                ~,
                "rules": '["blabla"],',

=or>        "rules": None,
=or>        "rules": '{"blabla"},',
=or>        "rules": "[]",
=or>        "rules": [],

                ~,
            },
        )
        seeder.execute()
```

**Error**
```
  File "/usr/local/lib/python3.8/site-packages/django_seed/guessers.py", line 109, in guess_format
    raise AttributeError(field)
AttributeError: models.class.rules
```

All cases corresponding to `=or>` have been put in, but the same error occurs. I think raise error occurs because it is not filtered from `if` at guessers.py.

I know that this is because it is an old version. Can you tell me how I can handle this with hardcoding?

I already checked the link below.
https://github.com/Brobin/django-seed/issues/36

**Comment by Brobin** [comment]
Sorry for the delay, just got it uploaded this morning
