### ISSUE TITLE
Field cannot be null, but actually, it can.

### ISSUE THREAD

**Issue by eriktelepovsky** [Brobin/django-seed#16]
I got this exception

```python
django_seed.exceptions.SeederException: Field myapp.MyModel.description cannot be null
```

everytime I run command:

```python
python manage.py seed myapp
```

**model definition**
```python
class MyModel(models.Model):
    description = models.TextField('description', blank=True, null=True, default=None)
```

Any ideas? Thank you.

*(using Django 1.8.3, Python 2.7.6, django-seed 0.1.3)*

**Comment by Brobin** [comment]
Does `MyModel` also have a foreign key to another model in your app?

**Comment by eriktelepovsky** [comment]
Yes it does. Seed for the app that foreign key model belongs to works fine.

**Comment by Brobin** [comment]
The foreign key is to another app? If so, this might be the issue.
Currently, foreign keys only work within an app. A fix is being worked on
in #12 to seed multiple apps at once.

**Comment by eriktelepovsky** [comment]
Yes, it is from another app. I cloned paulshannon's fork, branch flexible_applist, but another exception appears :/

```python
  File ".../django_seed/management/commands/seed.py", line 25, in add_argument
    self.option_list += ( make_option(*args, **kwargs), )
NameError: global name 'make_option' is not defined
```

**Comment by Brobin** [comment]
His branch is not yet complete. For the time being, I would recommend using the code version of seeding.

**Comment by eriktelepovsky** [comment]
I used code version of seeding:

```python
seeder.add_entity(MyModel, 10, {
    'foreign_key_column': lambda x: AnotherModel.objects.first()
})
seeder.execute()
```

but same exception occurs :/

Any other ideas? Thanks.

**Comment by Brobin** [comment]
Have you tried this?

    seeder.add_entity(AnotherModel, 10)
    seeder.add_entity(MyModel, 10)
    seeder.execute()

**Comment by housUnus** [comment]
still facing the same problem.
