### ISSUE TITLE
requirements are not up-to-date

### ISSUE THREAD

**Issue by coolharsh55** [Brobin/django-seed#21]
**requirements.txt** or **README** does not mention the following packages which are required to run tests:
 - coverage
 - django-nose
 - nose

This causes errors when executing `python runtests.py`

**Comment by Brobin** [comment]
fixed as of 725074e7798d77801a54b1cebdcdf4a5bc576a77

**Comment by coolharsh55** [comment]
Since these packages are not required for running django-seed, but only for tests, could they be stored in  `requirements_test.txt` instead? To keep the actual requirements separate?

**Comment by Brobin** [comment]
Fixed, thank you
