### ISSUE TITLE
remove warning suppression in management command for non-timezone aware datetimes

### ISSUE THREAD

**Issue by coolharsh55** [Brobin/django-seed#24]
The management command file `management/commands/seed.py` suppressed warning for non-timezone aware date times which is not documented or can simply be undesirable in outputs. Instead, the warnings should be shown **and / or** timezone support should be added for faked date time fields.

**Comment by Brobin** [comment]
Do you want it to use a random timezone? If not, your timezone format fix (fdb2b35a90f6169d4f23aca9b4d59ebb455b6d8f) should already support the timezone, we just need to remove the warning.

**Comment by coolharsh55** [comment]
I want the warnings to be explicitly shown instead of silently being ignored, so yes, removing the warnings would close this.
A random timezone would not be appropriate IMHO, since it can skew code checks that are timezone dependent. If the user specifically wants timezone aware objects without setting up a timezone, they can do it by configuring their date fields to be instantiated as time aware objects in the seeder.
