### ISSUE TITLE
Error with content_type ForeignKey

### ISSUE THREAD

**Issue by MarkWh1te** [Brobin/django-seed#35]
django_seed.exceptions.SeederException: Field product.QASection.content_type cannot be null

**Comment by notarock** [comment]
Same problem here using mysql.
Say I have item --foreign key --> member --foreign key --> store
it always fail when seeding item because member is seeded without a foreign key to store

**Comment by AngelOnFira** [comment]
I think this was resolved in #77, but if not, feel free to reopen this :ok_hand:
