### ISSUE TITLE
Problems with postgres fields

### ISSUE THREAD

**Issue by cyriac** [Brobin/django-seed#36]
Django now supports postgres fields like ArrayField, JSONField, HStoreField etc.

https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/

`seed` management command as well as `seeder.add_entity` fails since they are not been detected with `FieldTypeGuesser`.

It would be great to have this support at least at the `add_entity` level.

**Comment by Brobin** [comment]
Yep, this could be done fairly easily.

```
if django.VERSION[1] >= 9:
            if isinstance(field, ArrayField):
                return lambda x: provider.array_field()
```

Would require updates to the guesser and a provider.

**Comment by photonauta35** [comment]
is still not supported on postgres fields, right? (ArrayField, JSONField, HStoreField etc.)

**Comment by diego-capyba** [comment]
Any news about that? django-faker project doesn't seem to be updated anymore.

**Comment by AngelOnFira** [comment]
I'll see if I can take a look at this in the next week or so.

**Comment by AngelOnFira** [comment]
Ok, this should be resolved to *at least* not fail. #77 catches model types that do not have a guesser but does have a `_default_hint` ([here is the line](https://github.com/Brobin/django-seed/blob/6a31b8dd916aebc859ce50f6e7818c08d27034b7/django_seed/guessers.py#L114)), and  #80 allows you to pass a dict of objects that won't be handled by the guesser:

```python
seeder.add_entity(Player, 10, {
    'score':    lambda x: random.randint(0, 1000),
    'nickname': lambda x: seeder.faker.email(),
})
seeder.execute()
```

I'm going to close this issue, but please reopen if extra functionality is needed! :smiley:
