### ISSUE TITLE
Unrecognized Arguments: --number

### ISSUE THREAD

**Issue by blindpenguin** [Brobin/django-seed#37]
I just installed this lib and tried to create some fake data with the command provided by the documentation. But it fails with the following error:

```
python manage.py seed member --number=15
usage: manage.py seed [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
                      [--pythonpath PYTHONPATH] [--traceback] [--no-color]
                      app_label [app_label ...]
manage.py seed: error: unrecognized arguments: --number=15
```

Any idea what's going on?

django-seed Version: 0.1.6
Django: 1.10.2
Python: 3.5

**Comment by Brobin** [comment]
Yeah, this package is not yet compatible with Django 1.10. I think Django 1.10 deprecates one of the argument parsers.

**Comment by diogoosorio** [comment]
@Brobin I didn't bump the package version on the PR.

This should be fixed now, but it would be awesome if you could find the time to bump the version and publish the change on Pypi's repository. 😄

**Comment by Brobin** [comment]
updated!
