### ISSUE TITLE
pip install doesn't give management command

### ISSUE THREAD

**Issue by chadgh** [Brobin/django-seed#4]
Using Django 1.7.7 and Python 2.7.5 I did a pip install and the management command doesn't get installed. I even tried pip installing using `git+git://github.com/Brobin/django-seed.git` and that didn't work either.

**Comment by Brobin** [comment]
Good call, I missed that in `setup.py`. I'll get a fix up right away

**Comment by chadgh** [comment]
Great. pip installed using `git+git://github.com/Brobin/django-seed.git` after commit c33eb97. Works great. Thanks

**Comment by Brobin** [comment]
Sweet, just uploaded the fix to pypi too. Should work as of 0.1.2.
