### ISSUE TITLE
AttributeError: 'str' object has no attribute 'isoformat'

### ISSUE THREAD

**Issue by wakatoyee** [Brobin/django-seed#47]
`  File "/home/vagrant/.local/lib/python2.7/site-packages/django_seed/seeder.py", line 149, in execute
    entity = self.entities[klass].execute(using, inserted_entities)
  File "/home/vagrant/.local/lib/python2.7/site-packages/django_seed/seeder.py", line 92, in execute
    for field, field_format in self.field_formatters.items()
AttributeError: 'str' object has no attribute 'isoformat'`

This happens when running seeder.execute() upon ajax call.

**Comment by AngelOnFira** [comment]
This seems like it could be an artifact of Python 2.7. I'm going to close it, but if you are able to reproduce this on Python 3.x, and could give some more info such as a `pip freeze`, I can look into this further.
