### ISSUE TITLE
Getting unexpected SeederException for BooleanField

### ISSUE THREAD

**Issue by kevgathuku** [Brobin/django-seed#5]
I have a models file with the following field:
`active = models.BooleanField(default=True, blank=True)`

I also have also overriden the save method in this model as follows
```
def save(self):
        if datetime.date.today() > self.endDate:
            self.active = False
        if self.id:
            self.lastModified = datetime.datetime.now()
        else:
            pass
        super(Project, self).save()
```

When I run `python manage.py seed app_name --number=5`, I am always getting the following exception:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/kevin/.virtualenvs/aims/lib/python3.4/site-packages/django/core/ma
nagement/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/kevin/.virtualenvs/aims/lib/python3.4/site-packages/django/core/ma
nagement/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kevin/.virtualenvs/aims/lib/python3.4/site-packages/django/core/ma
nagement/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/kevin/.virtualenvs/aims/lib/python3.4/site-packages/django/core/ma
nagement/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/kevin/.virtualenvs/aims/lib/python3.4/site-packages/django/core/ma
nagement/base.py", line 565, in handle
    app_output = self.handle_app_config(app_config, **options)
  File "/home/kevin/.virtualenvs/aims/lib/python3.4/site-packages/django_seed/ma
nagement/commands/seed.py", line 38, in handle_app_config
    pks = seeder.execute()
  File "/home/kevin/.virtualenvs/aims/lib/python3.4/site-packages/django_seed/se
eder.py", line 133, in execute
    entity = self.entities[klass].execute(using, inserted_entities)
  File "/home/kevin/.virtualenvs/aims/lib/python3.4/site-packages/django_seed/se
eder.py", line 71, in execute
    setattr(obj, field, format(inserted_entities))
  File "/home/kevin/.virtualenvs/aims/lib/python3.4/site-packages/django_seed/se
eder.py", line 39, in build_relation
    raise SeederException(message)
django_seed.exceptions.SeederException: Field data_entry.Project.active cannot b
e null
```
Please help me figure out what may be the cause of this Exception.
I am using Django 1.8.1 and Python 3.4.3
Thanks in advance.

**Comment by Brobin** [comment]
This exception is thrown when there are missing relations. What are the other models in your app?

**Comment by kevgathuku** [comment]
You were right, the problem was with the relationships.
I have just found out that the problem is the `Project` model had relationships to models in another app. Therefore I had to run something like
`python manage.py seed other_app app_name` 
in order to get it to work.
Thanks.

**Comment by Brobin** [comment]
That might be a good idea. How does this sound?

**Note:** when seeding models with foreign keys, you must make sure that instances of those models exist, or that you seed them first.

**Comment by kevgathuku** [comment]
That sounds good to me. A small example though would be better.
Something like:
If you have an app 'A' that depends on models in another app 'B', make sure to seed app 'B' first before proceeding to seed 'A'.
But that can always be refined.

**Comment by Brobin** [comment]
Sounds good. I'll get that added!

**Comment by Brobin** [comment]
readme updated!
