### ISSUE TITLE
Not taking into account CharField with a max_length < 5

### ISSUE THREAD

**Issue by kevgathuku** [Brobin/django-seed#6]
I have the following model in one of my apps:
```python
class Currency(models.Model):
    abbrev = models.CharField(max_length=3, unique=True)
```
As the `CharField` is [currently implemented](https://github.com/Brobin/django-seed/blob/master/django_seed/guessers.py#L90), I am having problems getting a word that has a maximum length of 3

**Comment by Brobin** [comment]
This is an issue with faker. If you take a look at [the lorem provider source code](https://github.com/joke2k/faker/blob/master/faker/providers/lorem/__init__.py#L93) the minimum length is 5.

```python
if max_nb_chars < 5:
    raise ValueError('text() can only generate text of at least 5 characters')
```

Faker does have a currency provider. I would suggest trying something like this.

```python
from faker.provder.currency import Provider as CurrencyProvider

class Currency(models.Model):
    abbrev = models.CharField(choices=CurrencyProvider.currencies)

**Comment by Brobin** [comment]
Closing this for now. Reopen it if you have more issues

**Comment by kevgathuku** [comment]
Thanks for the suggestion to use the currency provider. I wasn't aware of it.
I'm not sure whether this is a related issue but I am now getting this error instead
`django.db.utils.IntegrityError: UNIQUE constraint failed: currencies.abbrev`
