### ISSUE TITLE
AttributeError: 'Generator' object has no attribute 'seed_instance'

### ISSUE THREAD

**Issue by MarvinKweyu** [Brobin/django-seed#69]
I cannot seem to get it to create data for any application I have so far.
```bash
python manage.py seed booking --number=15
```
Error message:
```bash
 cls.fakers[code].seed_instance(random.randint(1, 10000))
AttributeError: 'Generator' object has no attribute 'seed_instance'
```
Using **python3.8**

**Comment by AngelOnFira** [comment]
@MarvinKweyu I'm trying to figure out what might cause this, we have tests that are running on Python 3.8 that don't have the same issue. Would you be able to `pip freeze` for me? Also knowing what fields `booking` has would be useful. If the codebase is open source, I can also try debugging myself :smiley:

**Comment by AngelOnFira** [comment]
I'm thinking this might also have something to do with the language that you're using Django with.

```
You may specify a different locale by passing it in the constructor of the seeder. Defaults to settings.LANGUAGE_CODE

seeder = Seed.seeder(locale='sv_SE')
seeder.faker.city()  # 'Västerås'
```

If you could tell me the language in `settings.LANGUAGE_CODE`, that would also probably be helpful :100:

**Comment by MarvinKweyu** [comment]
Hey @AngelOnFira, it's been a while since I touched the repo, but I got to it! Since then, some items changed. However, I have tried running against the same model. It's a bummer I cannot replicate the same behavior as of now. I'll get a different error message from what this issue is tagged under, so it might be wrong labelling.

On my account model:
```python
class CustomUser(AbstractUser):
    email = models.EmailField(max_length=40, unique=True)
    --- # other fields

    is_client = models.BooleanField(default=True)
    is_receptionist = models.BooleanField(default=False)
    is_administrator = models.BooleanField(default=False)

    objects = UserManager()

    def __str__(self):
        return self.email

class Receptionist(models.Model):
    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, related_name="reception_profile"
    )
    --- # other fields
```

Running the app:
```bash
python manage.py seed accounts --number=15
```

```bash
django_seed.exceptions.SeederException: Field accounts.Receptionist.user cannot be null

```

The `not null` error messages seem to pop up in a couple of other models as well, but often after populating some data.
Again, I apologize for not being able to replicate this issue at this said time.

**Comment by AngelOnFira** [comment]
No worries, I understand that it's hard to replicate. The not null error is something I'm working on resolving for the next release. I'm going to close this issue for now, however, I'll keep it in the back of my mind in the case that I see behaviour similar to your original problem :100:
