### ISSUE TITLE
ImportError: No module named management.commands.seed

### ISSUE THREAD

**Issue by curtisstpierre** [Brobin/django-seed#7]
I'm attempting to use this to populate an app and I get the error:
ImportError: No module named management.commands.seed
I've attempted install from pip and from github

**Comment by Brobin** [comment]
Did you add `django_seed` to `INSTALLED_APPS`?

**Comment by curtisstpierre** [comment]
Yes, I've added it

**Comment by curtisstpierre** [comment]
The issue with this was that for whatever reason the commands folder didin't have a __init__.py file, when I added it, it seemed to work.

**Comment by Brobin** [comment]
Hmm, that's strange. For future reference, what version of pip and python are you using?

**Comment by curtisstpierre** [comment]
pip 6.1.1
python 2.7.9

**Comment by kevgathuku** [comment]
Also getting the same issue. Adding the `__init__.py` file in the management folder fixed it.

**Comment by Brobin** [comment]
I don't understand why this is happening. It might be an issue with setuputils or pip. As you can see, `___init__.py` does exist in [the management folder](https://github.com/Brobin/django-seed/tree/master/django_seed/management).

**Comment by Brobin** [comment]
I think I may have found the solution. In setup.py

```python
packages=['django_seed', 'django_seed.management.commands'],
```

should be

```python
packages=['django_seed', 'django_seed.management', 'django_seed.management.commands'],
```

Including the management package should make sure the `__init__.py` file is not omitted. I will make this change tonight if I get a chance.

**Comment by BooBSD** [comment]
Please, update pip version.

**Comment by Brobin** [comment]
Will do. Just got back from vacation :)

**Comment by Brobin** [comment]
Uploaded to pypi
