### ISSUE TITLE
pip install django-seed 'ascii' codec can't decode byte 0xc3 in position 3008: ordinal not in range(128)

### ISSUE THREAD

**Issue by MarinaaaniraM** [Brobin/django-seed#70]
**pip3 install django-seed==0.2.2**

Collecting django-seed
  Using cached django-seed-0.2.2.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ne1krphb/django-seed/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ne1krphb/django-seed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w9lxjy_t
         cwd: /tmp/pip-install-ne1krphb/django-seed/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ne1krphb/django-seed/setup.py", line 59, in <module>
        long_description=open('README.rst', 'r').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3008: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

python --version
**Python 3.6.9**

pip --version
pip 20.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)

**Comment by cccaballero** [comment]
Exactly same issue here, using Python 3.6.8

**Comment by baloda** [comment]
Hi @Brobin 
I see these changes are not present in version 0.2.2. Please update your PyPI module with the latest python code.

**Comment by AngelOnFira** [comment]
@baloda There have been a lot of changes to the master branch that haven't been deployed yet. I'm worried about regressions in some areas, so I'm trying to work through them first. If you need this functionality, please lock your version to a git commit for the time being.
