### ISSUE TITLE
Seeder fails with PostgreSQL ArrayField

### ISSUE THREAD

**Issue by Simouche** [Brobin/django-seed#83]
the seeder throws an error when it tries to seed this field:
`    phones = ArrayField(base_field=models.CharField(
            _("Phone Number"),
            max_length=50,
            validators=[phone_validator],
            unique=True,
        ))`

isn't it supported?

**Comment by AngelOnFira** [comment]
@Simouche can you post the error? I'll look into it, but any fields that aren't supported should at least use defaults. This might not be merged into the PyPi version yet, I'm trying to work through a lot of the current issues before the next release.

**Comment by Simouche** [comment]
it just just an `AttributeError` that you mentioned in the readme, but the real issue is: if i try to use the manual way of providing
a custom function with lambda in a dict, it still throws an error.
i worked arround this by;
- accessing your guessers.py code.
- added this field import to the imports: `from django.contrib.postgres.fields import ArrayField`
- added this case to the end of the guess_format method, just before throwing the exception: ` if isinstance(field,ArrayField): return lambda x: [faker.text()]`
this solved my issue just for this moment.

I'd be glad to help you implement the case of the Postgres ArrayField.

**Comment by elebumm** [comment]
I am running into this same issue but with the Django Gis Point field.
