### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by siuglukas** [Brobin/django-seed#87]
Gives error when installing with pip:

    ERROR: Command errored out with exit status 1:
     command: 'c:\users\pc\pycharmprojects\django\vuedjango\venv\scripts\python.exe' -c 'import sys, setuptools, token
ize; sys.argv[0] = '"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-wpmmq_lk\\django-seed\\setup.py'"'"'; __file_
_='"'"'C:\\Users\\PC\\AppData\\Local\\Temp\\pip-install-wpmmq_lk\\django-seed\\setup.py'"'"';f=getattr(tokenize, '"'"'
open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__,
'"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\PC\AppData\Local\Temp\pip-pip-egg-info-npo8uz2r'
         cwd: C:\Users\PC\AppData\Local\Temp\pip-install-wpmmq_lk\django-seed\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PC\AppData\Local\Temp\pip-install-wpmmq_lk\django-seed\setup.py", line 59, in <module>
        long_description=open('README.rst', 'r').read(),
      File "C:\Users\PC\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1257.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0xa5 in position 3015: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by AngelOnFira** [comment]
Can you edit this to make it a bit more readable?

Also can you run `python --version` as well as `pip freeze`? What command did you use to install?

**Comment by AngelOnFira** [comment]
Oh, it's because deciding the Readme isn't working. I made a fix for this while ago, but the Pypi version hasn't been updated yet. Your best bet for the time being would be to install Django-seed from Master, but I can get a specific commit where this is fixed if you want to lock it down.

**Comment by siuglukas** [comment]
Ok thank you for your response. The task that l wanted to do with seed was very small so l just found another package.
