### ISSUE TITLE
django.db.utils.DataError: value too long for type character varying(50)

### ISSUE THREAD

**Issue by kevgathuku** [Brobin/django-seed#9]
I'm getting this error while trying to seed this model:
```python
class Contact(models.Model):
    telephone = models.CharField(max_length=50, null=True, blank=True)
    mobile_phone = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    postal_code = models.CharField(max_length=50, null=True, blank=True)
    email_address = models.EmailField(max_length=100, blank=False, null=False)
    website = models.URLField(null=True, blank=True)
```
I suspect this is due to the address field, since `faker.address()` may return an address longer than 50 chars.

**Comment by Brobin** [comment]
Yeah, the length is the issue. Is there a reason why you are setting the
max length to 50? I think many addresses will be longer than that.

**Comment by kevgathuku** [comment]
For my particular case ths was a different sort of address.
Anyway I was just thinking it should honor the `max_length` argument by default

**Comment by Brobin** [comment]
The address provider in faker does not honor the max_length field. To make this work for your case, I recommend using the code version of seeding.

```python
seeder.add_entity(Contact, 10, {
    'address': lambda x: seeder.faker.word(50),
})
seeder.execute()
```

**Comment by kevgathuku** [comment]
Thanks. I'll try out this version.

**Comment by kenju254** [comment]
@andela-kndungu try adding more space to the max_field I go the same as well in a certain application i was building and that solved the issue.

**Comment by mxlian** [comment]
UPDATE: With the new faker library now you'll need the function `text` instead of `word` to work
```
seeder.add_entity(Contact, 10, {
    'address': lambda x: seeder.faker.text(50),
})
```
