### ISSUE TITLE
fake-factory dependency error

### ISSUE THREAD

**Issue by finavyad** [Brobin/django-seed#92]
Command: 
`seeder = Seed.seeder()`
Error:
```
ImportError: The ``fake-factory`` package is now called ``Faker``.
Please update your requirements.
```

**Comment by AngelOnFira** [comment]
Hmm, would I be able to get some info from you?

`python --version` (`python3` if that's the command you use instead)

and

`pip freeze`

We should be using an up-to-date Faker, but this will help me figure it out some more.

**Comment by AngelOnFira** [comment]
Looks like we still use fake-factory for the tests, but that shouldn't affect you.

**Comment by AngelOnFira** [comment]
Closing due to the lack of follow-up.
